version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      build:
        - restore_cache:
            - keys:
                - v1-dependencies-{{checksum "pom.xml"}}
                - v1-dependencies-
        - run: mvn install -DskipTests